Created deploy_update.py script which will generate a Dockerfile and installation file based on required conda environments and packages, etc.

diff --git a/deploy/template_install b/deploy/template_install
--- a/deploy/template_install
+++ b/deploy/template_install
@@ -8,19 +8,19 @@
 FILENAME="jupyter-vcdat_logfile.txt"
 
 # base conda channels
-BASE_CHANNELS="-c conda-forge"
+BASE_CHANNELS="$_base_channels"
 
 # dev conda channels to use
-DEV_CHANNELS="-c cdat/label/v82" #Change to '-c cdat/label/nightly' when nightly is ready
+DEV_CHANNELS="$_dev_channels" #Change to '-c cdat/label/nightly' when nightly is ready
 
 # user conda channels (stable)
-USER_CHANNELS="-c cdat/label/v82"
+USER_CHANNELS="$_user_channels"
 
 # base packages
-BASE_PKGS="pip vcs tqdm nodejs 'python=3.7' jupyterlab jupyterhub ipywidgets"
+BASE_CONDA_PKGS="$_base_conda_pkgs"
 
 # dev and test packages
-DEV_PKGS="testsrunner cdat_info"
+DEV_CONDA_PKGS="$_dev_conda_pkgs"
 
 # default env name
 REQUESTED_ENV_NAME="jupyter-vcdat"
@@ -33,7 +33,7 @@ INSTALL_MODE="USER"
 
 # conda channel and CONDA_PACKAGES to use
 CONDA_CHANNELS="$USER_CHANNELS $BASE_CHANNELS"
-CONDA_PACKAGES=$BASE_PKGS
+CONDA_PACKAGES=$BASE_CONDA_PKGS
 
 function usage() {
   cat << EOF
@@ -47,7 +47,7 @@ optional arguments:
   -v VERBOSE
                         Also prints output to screen
   -d DEVELOPER
-                        Installs latest nightly version with test suite tools for developers
+                        Installs developer version with developer tools
   -n CONDA_ENV_NAME, --name CONDA_ENV_NAME
                         Name of the conda environment to install in (will create if not existing)
 EOF
@@ -56,24 +56,24 @@ exit 0
 
 # Figure out command line arguments: http://linuxcommand.org/lc3_wss0120.php
 while [ "$1" != "" ]; do
-    case $1 in
-        -f | --file )           shift
-                                FILENAME=$1
-                                ;;
-        -v | --VERBOSE )        VERBOSE=1
-                                ;;
-        -n | --name ) shift
-                                REQUESTED_ENV_NAME=$1
-                                ;;
-        -d | --dev ) shift
-                                INSTALL_MODE="DEV"
-                                ;;
-        -h | --help )           usage
-                                ;;
-        * )                     usage
-                                exit 1
-    esac
-    shift
+  case $1 in
+    -f | --file ) shift
+                            FILENAME=$1
+                            ;;
+    -v | --VERBOSE )        VERBOSE=1
+                            ;;
+    -n | --name ) shift
+                            REQUESTED_ENV_NAME=$1
+                            ;;
+    -d | --dev )
+                            INSTALL_MODE="DEV"
+                            ;;
+    -h | --help )           usage
+                            ;;
+    * )                     usage
+                            exit 1
+  esac
+  shift
 done
 
 echo "Installing jupyter-vcdat extension in conda env: '${REQUESTED_ENV_NAME}' (you can change this via -c option)"
@@ -81,7 +81,7 @@ echo "Installing jupyter-vcdat extension in conda env: '${REQUESTED_ENV_NAME}' (
 # Choose conda channels and packages based on installion mode
 if [ $INSTALL_MODE == "DEV" ]; then
   CONDA_CHANNELS="$DEV_CHANNELS $BASE_CHANNELS"
-  CONDA_PACKAGES="$BASE_PKGS $DEV_PKGS"
+  CONDA_PACKAGES="$BASE_CONDA_PKGS $DEV_CONDA_PKGS"
 fi
 
 echo "Using following conda channels: '${CONDA_CHANNELS}'"
@@ -90,7 +90,6 @@ echo "Output will be redirected to: '$FILENAME' (you can control the FILENAME wi
 if [ $VERBOSE == 1 ]; then
   # Redirect stdout ( > ) into a named pipe ( >() ) running "tee"
   exec > >(tee -i $FILENAME)
-
 else
   echo "Going into quiet mode, suppressing output"
   echo "For verbose mode run with -v option"
@@ -103,6 +102,7 @@ else
   # Open STDOUT as $LOG_FILE file for read and write.
   exec 1<>$FILENAME
 fi
+
 # Without this, only stdout would be captured - i.e. your
 # log file would not contain any error messages.
 exec 2>&1
@@ -116,36 +116,38 @@ set -o pipefail
 set -E
 set -o functrace
 function handle_error {
-    local retval=$?
-    local line=${last_lineno:-$1}
-    echo "Failed at $line: $BASH_COMMAND"
-    echo "Trace: " "$@"
-    echo "return code: " "$?"
-    exit $retval
- }
+  local retval=$?
+  local line=${last_lineno:-$1}
+  echo "Failed at $line: $BASH_COMMAND"
+  echo "Trace: " "$@"
+  echo "return code: " "$?"
+  exit $retval
+}
 trap 'handle_error $LINENO ${BASH_LINENO[@]}' ERR
 
 CONDA_EXE="$(which conda)"
 
+# Activate requested conda environment
 if [ ${CONDA_DEFAULT_ENV:-"NA"} != ${REQUESTED_ENV_NAME} ]; then
-    echo "Current conda does not match requested conda: ${CONDA_DEFAULT_ENV:-'NA'} vs ${REQUESTED_ENV_NAME}"
-    envs=$(${CONDA_EXE} env list | cut -d ' ' -f1)
-    found=0
-    for a_env in $envs
-    do
-        if [ $a_env == ${REQUESTED_ENV_NAME} ]; then
-            found=1
-        fi
-    done
-    if [ $found == 1 ]; then
-        echo "ACTIVATING existing env: ${REQUESTED_ENV_NAME}"
-        source activate ${REQUESTED_ENV_NAME}
-    else
-        echo "The requested env ${REQUESTED_ENV_NAME} does not seem to exist we will create it."
+  echo "Current conda does not match requested conda: ${CONDA_DEFAULT_ENV:-'NA'} vs ${REQUESTED_ENV_NAME}"
+  envs=$(${CONDA_EXE} env list | cut -d ' ' -f1)
+  found=0
+  for a_env in $envs
+  do
+    if [ $a_env == ${REQUESTED_ENV_NAME} ]; then
+      found=1
     fi
+  done
+  if [ $found == 1 ]; then
+    echo "ACTIVATING existing env: ${REQUESTED_ENV_NAME}"
+    conda activate ${REQUESTED_ENV_NAME}
+  else
+    echo "The requested env ${REQUESTED_ENV_NAME} does not seem to exist we will create it."
+  fi
 fi
 
 if [ ${CONDA_DEFAULT_ENV:-"NA"} != ${REQUESTED_ENV_NAME} ]; then
+  # If requested conda environment doesn't exist, create it
   echo "Creating conda env: ${REQUESTED_ENV_NAME}"
   conda config --set channel_priority strict
   echo "conda create -y -n ${REQUESTED_ENV_NAME} $CONDA_CHANNELS $CONDA_PACKAGES"
@@ -153,44 +155,24 @@ if [ ${CONDA_DEFAULT_ENV:-"NA"} != ${REQUESTED_ENV_NAME} ]; then
   CONDA_BASE=$(conda info --base)
   source $CONDA_BASE/etc/profile.d/conda.sh
   conda activate ${REQUESTED_ENV_NAME}
-
-  # Install sidecar
-  python -m pip install sidecar || pip install sidecar
-
-  # Install dev packages if needed
-  if [ $INSTALL_MODE == "DEV" ]; then
-    python -m pip install selenium || pip install selenium
-    python -m pip install pyvirtualdisplay || pip install pyvirtualdisplay
-  fi
-
-  # Install extensions
-  jupyter labextension install @jupyter-widgets/jupyterlab-manager
-  jupyter labextension install @jupyter-widgets/jupyterlab-sidecar
-  jupyter labextension install jupyterlab-tutorial-extension
-  jupyter labextension install @jupyterlab/hub-extension
-  jupyter labextension install jupyterlab-favorites
+else
+  # Install required conda packages into existing environment
+  echo "Installing conda packages in  environment: ${REQUESTED_ENV_NAME}"
+  conda config --set channel_priority strict
+  echo "conda install -y $CONDA_CHANNELS $CONDA_PACKAGES"
+  conda create -y $CONDA_CHANNELS $CONDA_PACKAGES
 fi
 
-# We need to allow pipe to break in case we are not in a git repo directory
-# set +o pipefail
-# REMOTE=$(git config --get remote.origin.url) || REMOTE="NO"
-# echo "REMOTE: $REMOTE"
-# PROTOCOL_SEP=${REMOTE:3:1}
-# echo "PROTOCOL SEPARATOR: $PROTOCOL_SEP"
-# if [[ $PROTOCOL_SEP == "@" ]]; then
-#     NDELIM=2
-# else
-#     NDELIM=5
-# fi
-# echo "NDELIM: $NDELIM"
-# REPO=$(echo $REMOTE | cut -d '/' -f $NDELIM) || REPO="NO"
-# echo "REPO:$REPO"
-# set -o pipefail
+# Install sidecar
+$_base_pip_install
 
-# if [[ $REPO != "jupyter-vcdat" && $REPO != "jupyter-vcdat.git" ]]; then
-#   git clone git://github.com/CDAT/jupyter-vcdat.git
-#   cd jupyter-vcdat
-# fi
+# Install dev packages if needed
+if [ $INSTALL_MODE == "DEV" ]; then
+$_dev_pip_install
+fi
+
+# Install extensions
+$_install_extensions
 
 # Install jupyter-vcdat extension
 npm install
